### ISSUE TITLE
Add directory to $PATH

### ISSUE THREAD

**Issue by mauricios** [Aplyca/ansible-role-essentials#1]
This can be done by adding a file (to the `/etc/profile.d`) with the PATH inclusion using a template , like this:

``` bash
# set PATH so it includes my dir bin if it exists
if [ -d "/my/dir/bin" ] ; then
    PATH="/my/dir/bin:$PATH"
fi
```

**Comment by mauricios** [comment]
+1 this can be useful to add bin directories from installed apps, e. g. `/var/www/app/bin`, so the app binaries will be available anywhere.

**Comment by damaya** [comment]
This is similar to the default ~/.profile file which contains:
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

**Comment by damaya** [comment]
First working version of the template is here https://github.com/Aplyca/ansible-role-essentials/blob/e1/templates/etc/profile.d/profile.j2 i forgot use vars, and the task (Add directory to path) is pointing to the destiny with same template path: /etc/profile.d, not sure if should be ~/.profile, or if both are wrong, please let me know if i misunderstood the issue.

**Comment by mauricios** [comment]
There is a pull request for this:  https://github.com/Aplyca/ansible-role-essentials/pull/5, how can be this related to this issue?
